name: build_pubspec_example
description: This is an example description. Great job! Awesome package.
publish_to: 'none'
authors:
  - Theo Zapata <theozap77400@gmail.com>

version: 0.1.2

environment:
  sdk: ">=2.1.0 <3.0.0"

dev_dependencies:
  build_runner: ^1.0.0
  build_pubspec:
    path: ../../

env:
  toto: 'test'
  user: '$USER'
  path: '$(pwd)'
  complex: 'test $HOME and $(ls)'


