name: build_pubspec_example
description: This is an example description. Great job! Awesome package.
publish_to: 'none'
authors:
  - Theo Zapata <theozap77400@gmail.com>

version: 0.1.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  build_runner: ^2.1.2
  build_env_pubspec:
    path: ../../

flutter:
  uses-material-design: true

env:
  toto: 'test'
  user: '$USER'
  path: '$(pwd)'
  complex: 'test $HOME and $(ls)'


